# Gene-level summarization with tximport
## Summarize transcript-level quantification to gene-level counts/TPM
```
library(tximport)

samples <- read_tsv("samples.tsv", show_col_types = FALSE)
files <- file.path(samples$salmon_dir, "quant.sf")

tx2gene <- read_tsv("tx2gene.tsv",
                    col_names = c("transcript_id","gene_id"),
                    show_col_types = FALSE)

txi <- tximport(files, type = "salmon", tx2gene = tx2gene,
                countsFromAbundance = "lengthScaledTPM",
                ignoreTxVersion = TRUE)
```

### Code Explanation:
· **samples.tsv**: a tab-delimited file like:
```
sample_id condition salmon_dir
S1 A /path/to/S1
S2 A /path/to/S2
S3 B /path/to/S3
```
At minimum, it should include `sample_id`, `salmon_dir`.

· **quant.sf**: Output file generated by Salmon for each sample, containing transcript-level abundance estimates (TPM, NumReads, EffectiveLength).  
These files serve as the input for gene-level summarization.  

· **tx2gene.tsv**: a tab-delimited file like:
```
transcript_id gene_id
ENST00000456328 ENSG00000223972
ENST00000450305 ENSG00000223972
ENST00000515242 ENSG00000227232
```
At minimum, it should include `transcript_id` and `gene_id`.  

**Note**: Use the same reference annotation (version) as used to build the Salmon index to ensure consistent ID mapping. 
